name: Practicum
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - ipykernel
  - ipython
  - ipython_genutils
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - requests
  - nest-asyncio
  - python=3.9
  # Добавлено мной
  - postgresql
  - jupyter_contrib_nbextensions # После установки необходимо активировать командой jupyter contrib nbextension install --user
  - jupyter_nbextensions_configurator # После установки необходимо активировать командой jupyter nbextensions_configurator enable --user
  - notebook==6.4.0 # Необходимо для корректрой работы nbextensions
  - pip:
    - beautifulsoup4==4.9.3
    - matplotlib==3.3.4
    - nltk==3.6.1
    - numpy==1.20.1
    - pandas==1.2.4
    - plotly==5.4.0
    - psycopg2-binary==2.9.2
    - regex==2022.3.15
    - scikit-learn==0.24.1
    - scipy==1.8.0
    - seaborn==0.11.1
    - sqlalchemy==1.4.15
    - statsmodels==0.13.2
    - catboost==1.0.3
    - pyspark==3.0.2
    - torch==1.10.0
    - transformers==4.12.5
    - pillow==8.4.0 
    - keras==2.7.0
    - tensorflow==2.7.0
    # Добавлено мной
    - traitlets<5.10 # Необходимо для корректрой работы Jupyter